// Generated by bilt-cloud from this project's database schema. Do not edit.
// Regenerated on every schema change; edits are overwritten.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

declare module '@biltme/backend' {
  interface Database {
    public: {
      Tables: {
        merchants: {
          Row: {
            id: string
            user_id: string
            business_name: string
            existing_pos: string
            stellar_wallet: string
            card_processing_rate: number
            created_at: string
          }
          Insert: {
            id?: string
            user_id: string
            business_name: string
            existing_pos: string
            stellar_wallet: string
            card_processing_rate?: number
            created_at?: string
          }
          Update: {
            id?: string
            user_id?: string
            business_name?: string
            existing_pos?: string
            stellar_wallet?: string
            card_processing_rate?: number
            created_at?: string
          }
          Relationships: []
        }
        payment_sessions: {
          Row: {
            id: string
            merchant_id: string
            public_token: string
            amount_gbp: number
            order_reference: string | null
            asset_code: string
            asset_issuer: string | null
            settlement_amount: number
            platform_fee_bps: number
            merchant_amount: number
            platform_fee: number
            merchant_wallet: string
            platform_wallet: string | null
            status: Database['public']['Enums']['payment_status']
            payer_address: string | null
            stellar_transaction_hash: string | null
            failure_reason: string | null
            settlement_mode: string
            expires_at: string
            settled_at: string | null
            created_at: string
          }
          Insert: {
            id?: string
            merchant_id: string
            public_token: string
            amount_gbp: number
            order_reference?: string | null
            asset_code?: string
            asset_issuer?: string | null
            settlement_amount: number
            platform_fee_bps?: number
            merchant_amount: number
            platform_fee: number
            merchant_wallet: string
            platform_wallet?: string | null
            status?: Database['public']['Enums']['payment_status']
            payer_address?: string | null
            stellar_transaction_hash?: string | null
            failure_reason?: string | null
            settlement_mode?: string
            expires_at: string
            settled_at?: string | null
            created_at?: string
          }
          Update: {
            id?: string
            merchant_id?: string
            public_token?: string
            amount_gbp?: number
            order_reference?: string | null
            asset_code?: string
            asset_issuer?: string | null
            settlement_amount?: number
            platform_fee_bps?: number
            merchant_amount?: number
            platform_fee?: number
            merchant_wallet?: string
            platform_wallet?: string | null
            status?: Database['public']['Enums']['payment_status']
            payer_address?: string | null
            stellar_transaction_hash?: string | null
            failure_reason?: string | null
            settlement_mode?: string
            expires_at?: string
            settled_at?: string | null
            created_at?: string
          }
          Relationships: [
            {
              foreignKeyName: 'payment_sessions_merchant_id_fkey'
              columns: ['merchant_id']
              isOneToOne: false
              referencedRelation: 'merchants'
              referencedColumns: ['id']
            },
          ]
        }
        platform_settings: {
          Row: {
            id: boolean
            network: string
            platform_fee_bps: number
            platform_wallet: string | null
            settlement_asset_code: string
            settlement_asset_issuer: string | null
            xlm_gbp_rate: number
            settlement_cost_pct: number
            soroban_contract_id: string | null
            updated_at: string
          }
          Insert: {
            id?: boolean
            network?: string
            platform_fee_bps?: number
            platform_wallet?: string | null
            settlement_asset_code?: string
            settlement_asset_issuer?: string | null
            xlm_gbp_rate?: number
            settlement_cost_pct?: number
            soroban_contract_id?: string | null
            updated_at?: string
          }
          Update: {
            id?: boolean
            network?: string
            platform_fee_bps?: number
            platform_wallet?: string | null
            settlement_asset_code?: string
            settlement_asset_issuer?: string | null
            xlm_gbp_rate?: number
            settlement_cost_pct?: number
            soroban_contract_id?: string | null
            updated_at?: string
          }
          Relationships: []
        }
        transactions: {
          Row: {
            id: string
            payment_session_id: string
            merchant_id: string
            stellar_transaction_hash: string
            payer_address: string
            asset_code: string
            asset_issuer: string | null
            gross_amount: number
            merchant_amount: number
            platform_fee: number
            amount_gbp: number
            platform_fee_bps: number
            ledger: number | null
            settlement_mode: string
            created_at: string
          }
          Insert: {
            id?: string
            payment_session_id: string
            merchant_id: string
            stellar_transaction_hash: string
            payer_address: string
            asset_code: string
            asset_issuer?: string | null
            gross_amount: number
            merchant_amount: number
            platform_fee: number
            amount_gbp: number
            platform_fee_bps: number
            ledger?: number | null
            settlement_mode?: string
            created_at?: string
          }
          Update: {
            id?: string
            payment_session_id?: string
            merchant_id?: string
            stellar_transaction_hash?: string
            payer_address?: string
            asset_code?: string
            asset_issuer?: string | null
            gross_amount?: number
            merchant_amount?: number
            platform_fee?: number
            amount_gbp?: number
            platform_fee_bps?: number
            ledger?: number | null
            settlement_mode?: string
            created_at?: string
          }
          Relationships: [
            {
              foreignKeyName: 'transactions_merchant_id_fkey'
              columns: ['merchant_id']
              isOneToOne: false
              referencedRelation: 'merchants'
              referencedColumns: ['id']
            },
            {
              foreignKeyName: 'transactions_payment_session_id_fkey'
              columns: ['payment_session_id']
              isOneToOne: false
              referencedRelation: 'payment_sessions'
              referencedColumns: ['id']
            },
          ]
        }
      }
      Views: { [_ in never]: never }
      Functions: {
        current_merchant_id: {
          Args: Record<PropertyKey, never>
          Returns: string
        }
      }
      Enums: {
        payment_status: 'pending' | 'wallet_connected' | 'authorising' | 'submitted' | 'settled' | 'failed' | 'expired'
      }
      CompositeTypes: { [_ in never]: never }
    }
  }
}
